language: java
jdk:
- openjdk11
cache:
  directories:
  - "$HOME/.m2"
  - "$HOME/.gradle"
deploy:
  provider: heroku
  app: tax-cc
  api_key:
    secure: c2spP0YIHwiO81xDOumww7qw6dJPypqLrWvk6rYbRpDqfn11KKc0Yd7e9VGZkqqLllm1AO9mS20NzoQOzNFln+8Zvg5RbNhMU/vTdzbbsBjC5J5tcB9Dkf7kAgpj7KVWjufx5U1e5+9np5PvK+vRQZNft30EBzsMs9rxc2FP7bauOiRLrkbY6+a3CkG48tG2O0VCgQYEHOxTh8oYKStWQ4bv+6KRuD6JvFrnkya91/2Y4z2vm5vY2JmW4FMJUwxXCEYKxK/09wn8tbadxgiw7CrOcIWFK//n2ESM0OrmCwFO69c1bjmSJPMFHuJAJuHhwBklf7Gk2/jViHC9HBHAvFJ9C3FYu9Z63Q7tEgqmAYXkuRRwp3ePCngVNIh9u+bMdKDnYsEmSsIFuj6FN+hsF09JNTV1J8/RzSloi64Wl0jiP+HJmwX7UTxDu4VyFRyAVQrBhnVcsHQOVVx2yvmdFmleXtGquV2oP0N2sooF8B/M8chyEeB6qlBbINuoO7284aq5xNop8r87QICF7DCMTL6etDxLlkyLwx4PBaky9p51BifYNnAM50ZZ3FtCt1oJ3R56ekYXwwFZeMd6bPgtX59fZpDUJAnaZ8bX8YLDxBMlhncijthfDJCh74lWT6GKXTeOF15cKHP5gbXVkFyZ2jqCQPkQZfN84b0p/oPonKE=
